### ISSUE TITLE
Ctrl-d to delete the current entry

### ISSUE THREAD

**Issue by danihodovic** [m42e/zsh-histdb-fzf#7]
Would you consider adding a ctrl-d default key binding for deleting the current entry?

```
ctrl-d:execute(source ~/.zinit/plugins/larkery---zsh-histdb/sqlite-history.zsh && histdb --forget {}
```

As per https://github.com/larkery/zsh-histdb/issues/25#issuecomment-881024850

**Comment by m42e** [comment]
Sounds interesting hey did. you close is?
